# Generated by aeris-theme. Imported from dotfiles/alacritty/alacritty.toml.
[colors.primary]
background = "{{ background }}"
foreground = "{{ foreground }}"

[colors.cursor]
text = "{{ background }}"
cursor = "{{ bright_foreground }}"

[colors.vi_mode_cursor]
text = "{{ background }}"
cursor = "{{ bright_foreground }}"

[colors.selection]
text = "{{ bright_foreground }}"
background = "{{ selection }}"

[colors.search.matches]
foreground = "{{ background }}"
background = "{{ yellow }}"

[colors.search.focused_match]
foreground = "{{ background }}"
background = "{{ red }}"

[colors.footer_bar]
foreground = "{{ background }}"
background = "{{ foreground }}"

[colors.normal]
black   = "{{ background }}"
red     = "{{ red }}"
green   = "{{ green }}"
yellow  = "{{ yellow }}"
blue    = "{{ blue }}"
magenta = "{{ magenta }}"
cyan    = "{{ cyan }}"
white   = "{{ foreground }}"

[colors.bright]
black   = "{{ muted }}"
red     = "{{ bright_red }}"
green   = "{{ bright_green }}"
yellow  = "{{ bright_yellow }}"
blue    = "{{ bright_blue }}"
magenta = "{{ bright_magenta }}"
cyan    = "{{ bright_cyan }}"
white   = "{{ bright_foreground }}"
