# Generated by aeris-theme. Included from dotfiles/foot/foot.ini.
#
# The section is [colors-dark], not [colors] — foot has no plain [colors]
# section and silently ignores one, falling back to its built-in palette.
# foot defaults to the dark theme whatever the palette's own mode is, so a
# light theme goes here too; the section name is just the slot foot reads.
[colors-dark]
foreground={{ foreground_strip }}
background={{ background_strip }}
selection-foreground={{ bright_foreground_strip }}
selection-background={{ selection_strip }}

cursor={{ background_strip }} {{ bright_foreground_strip }}

regular0={{ background_strip }}
regular1={{ red_strip }}
regular2={{ green_strip }}
regular3={{ yellow_strip }}
regular4={{ blue_strip }}
regular5={{ magenta_strip }}
regular6={{ cyan_strip }}
regular7={{ foreground_strip }}

bright0={{ muted_strip }}
bright1={{ bright_red_strip }}
bright2={{ bright_green_strip }}
bright3={{ bright_yellow_strip }}
bright4={{ bright_blue_strip }}
bright5={{ bright_magenta_strip }}
bright6={{ bright_cyan_strip }}
bright7={{ bright_foreground_strip }}
