# Generated by aeris-theme. Included from dotfiles/fuzzel/fuzzel.ini.
#
# fuzzel colors are RGBA hex with no leading '#', hence _strip plus an
# explicit alpha byte. f2 on the background gives a little translucency.
[colors]
background={{ background_strip }}f2
text={{ foreground_strip }}ff
prompt={{ accent_strip }}ff
placeholder={{ muted_strip }}ff
input={{ bright_foreground_strip }}ff
match={{ accent_strip }}ff
selection={{ selection_strip }}ff
selection-text={{ bright_foreground_strip }}ff
selection-match={{ accent_strip }}ff
counter={{ muted_strip }}ff
border={{ accent_strip }}ff
