# Generated by aeris-theme. Sourced at the end of dotfiles/hypr/hyprland.conf,
# so these win over the defaults set there.
#
# Deliberately only the border colors: each key added here must be one that
# the installed Hyprland actually accepts, and an unknown key raises an error
# overlay at startup. Add more once you have confirmed them against your
# version.

general {
  col.active_border   = rgba({{ accent_strip }}ff)
  col.inactive_border = rgba({{ muted_strip }}aa)
}
