# Generated by aeris-theme. Included from dotfiles/kitty/kitty.conf.
foreground           {{ foreground }}
background           {{ background }}
selection_foreground {{ bright_foreground }}
selection_background {{ selection }}

cursor               {{ bright_foreground }}
cursor_text_color    {{ background }}

active_border_color  {{ accent }}
active_tab_background {{ accent }}

color0  {{ background }}
color1  {{ red }}
color2  {{ green }}
color3  {{ yellow }}
color4  {{ blue }}
color5  {{ magenta }}
color6  {{ cyan }}
color7  {{ foreground }}
color8  {{ muted }}
color9  {{ bright_red }}
color10 {{ bright_green }}
color11 {{ bright_yellow }}
color12 {{ bright_blue }}
color13 {{ bright_magenta }}
color14 {{ bright_cyan }}
color15 {{ bright_foreground }}
